### ISSUE TITLE
Which Late-Night (After Midnight) Boulder Restaurant Has The Best Food?

### ISSUE THREAD

**Issue by JoshFerge** [CSCI-4830-002-2014/hackathon-yelp#4]

**Comment by adrian-chen** [comment]
In Vegas, the Grand Lux Cafe has the highest rated food at 4 stars.

db.business.find({"city": "Las Vegas","categories": "Food", "attributes.Good For.latenight": true, $or:[{"hours.Friday.close":"01:00"},{"hours.Friday.close":"02:00"},{"hours.Friday.close":"03:00"},{"hours.Friday.close":"04:00"}]},{"stars":-1 , "name":1}).pretty()
